on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: A job to test react app
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: test action step
        uses: ./ # Uses an action in the root directory
        id: hello